#FROM --platform=linux/arm64 python:3.11-slim
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# need curl for health check
RUN apt-get update && apt-get install -y curl

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY MongoMCP/ MongoMCP/
COPY AWS_settings.py .
COPY mongo_mcp.py .

# Make the script executable
RUN chmod +x mongo_mcp.py

# Set environment variables
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

# Run the MCP server
CMD ["fastapi", "run", "mongo_mcp.py"]
